# Generated by Django 3.1.3 on 2022-03-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='visibility',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='private', max_length=100),
        ),
    ]
