# Generated by Django 3.1.3 on 2022-03-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsite', '0002_log_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='visibility',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], max_length=100),
        ),
    ]
