# Generated by Django 3.1.3 on 2022-03-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsite', '0004_auto_20220320_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='image',
            field=models.ImageField(upload_to='travelImages'),
        ),
    ]
