# Generated by Django 3.1.3 on 2022-03-21 21:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsite', '0005_auto_20220320_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
