# Generated by Django 3.1.3 on 2022-03-22 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsite', '0006_auto_20220322_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='LogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='travelImages/')),
                ('log', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myWebsite.log')),
            ],
        ),
    ]
