# Generated by Django 3.1.3 on 2022-03-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsite', '0007_auto_20220323_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logimage',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='log',
            name='image',
            field=models.ImageField(upload_to='travelImages/'),
        ),
    ]
